# Generated by Django 3.1.1 on 2020-09-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
